### ISSUE TITLE
Add to awesome-vctrs list?

### ISSUE THREAD

**Issue by krlmlr** [rossellhayes/fracture#9]
Looks like your package also implements a vector class that represents fractions. This would be a great fit for https://github.com/krlmlr/awesome-vctrs#numbers. Would you like to contribute a pull request?

**Comment by rossellhayes** [comment]
@krlmlr Thanks for reaching out! It's really cool to have my work noticed to include in such an awesome project. I've opened a PR:
* krlmlr/awesome-vctrs/pull/17
